### ISSUE TITLE
Uncaught TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by SeyeongPark** [SeyeongPark/read-my-code#3]
> polyfills.js:139 **Uncaught TypeError: Object prototype may only be an Object or null: undefined**
    at Function.setPrototypeOf (<anonymous>)
    at polyfills.js:139:1
    at patch (polyfills.js:141:1)
    at patch (graceful-fs.js:104:1)
    at Object.<anonymous> (graceful-fs.js:96:1)
    at ../../../node_modules/firebase-tools/node_modules/graceful-fs/graceful-fs.js (graceful-fs.js:429:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at ../../../node_modules/firebase-tools/node_modules/configstore/index.js (index.js:4:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at ../../../node_modules/firebase-tools/lib/configstore.js (configstore.js:4:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at ../../../node_modules/firebase-tools/lib/utils.js (utils.js:14:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at ../../../node_modules/firebase-tools/lib/api.js (api.js:8:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (index.jsx:237:1)
    at ./src/pages/Input/index.jsx (index.jsx:251:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (App.css?dde5:82:1)
    at ./src/App.js (App.js:26:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (index.css?bb0a:82:1)
    at ./src/index.js (index.js:11:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at 1 (Test.jsx:10:1)
    at __webpack_require__ (bootstrap:851:1)
    at checkDeferredModules (bootstrap:45:1)
    at Array.webpackJsonpCallback [as push] (bootstrap:32:1)
    at main.chunk.js:1:73

**Comment by SeyeongPark** [comment]
Somehow, it had put `import { consoleOrigin } from 'firebase-tools/lib/api';
` at 'Input/index.jsx'.

I assume that the reason why it got this error is I put the file which is for 'api' (backend) side, not the frontend.

After I delete the line, it works.
